### ISSUE TITLE
[bug] figcaption width is bugged

### ISSUE THREAD

**Issue by slashformotion** [isunjn/serene#19]
calling this shortcode gives
```
{{ figure(src="./sample.jpg", alt="A pbm image", caption="A sample Bit Map image.") }}
```

![image](https://github.com/isunjn/serene/assets/45801817/9292716f-0d03-41e8-9db2-2f9cf0eb37ba)

of in HTMl
```html
<figure>
<img alt="A pbm image" src="./sample.jpg" class="lightense-target">
<figcaption>A sample Bit Map image.</figcaption>
</figure>
```

figcaption is subject to the following css rule
```css
body.post article figcaption {
	width: min-content;
	margin: 5px auto;
}
```

I had to remove `width: min-content` to make it work
